# Test that we can build on Linux and MacOS with the conda-forge toolchain

name:  Test Compilation

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Compile on ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            arch: Linux-x86_64
          - os: macos-latest
            arch: MacOSX-x86_64
          - os: macos-latest
            arch: MacOSX-arm64
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Conda Base
        run: |
          sudo rm -rf /usr/share/miniconda \
            && sudo rm -rf /usr/local/miniconda \
            && curl -SL -o miniforge.sh https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-${{ matrix.arch }}.sh \
            && bash miniforge.sh -b -f -p ~/conda \
            && source ~/conda/etc/profile.d/conda.sh \
            && conda activate base \
            && conda update -n base --yes conda

      - name: Check Conda Config
        run: |
          source ~/conda/etc/profile.d/conda.sh \
            && conda activate base \
            && conda info \
            && conda list \
            && conda config --show-sources \
            && conda config --show

      - name: Install Dependencies
        run: |
          source ~/conda/etc/profile.d/conda.sh \
            && conda create --yes -n test cmake compilers

      - name: Install and Test
        run: |
          source ~/conda/etc/profile.d/conda.sh \
            && conda activate test \
            && mkdir -p build \
            && pushd build >/dev/null 2>&1 \
            && cmake -DCMAKE_INSTALL_PREFIX=${CONDA_PREFIX} .. \
            && make -j 2 install \
            && make test
